server:
  port: 9002

spring:
  application: 
    name: COURSE-SERVICE
  datasource:
    url: jdbc:mysql:///hrm-course? serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8

hrm:
  swagger:
    title: 课程管理服务
    description: 课程管理服务接口文档

#feign:
  #hystrix:
   # enabled: true
   # command:
     # default:
     #   execution:
         # isolation:
           # thread:
            #  timeoutInMilliseconds: 4000 # 设置hystrix的超时时间为5000ms