server:
  port: 9006

spring:
  datasource:
    url: jdbc:mysql:///hrm-page? serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8

hrm:
  swagger:
    title: 页面管理服务
    description: 页面管理服务接口文档